PEER_SERVER_DEFAULT_PORT = 6881
PEER_SERVER_MAX_CONNECTION = 10
PEER_SERVER_TIMEOUT = 3

METAINFO_FILE_PATH = "metainfo/"
REPO_FILE_PATH = "repo/"

ANNOUNCE_INTERVAL = 60

TEMP_DOWNLOAD_FILE_EXTENSION = ".temp"

PEER_CLIENT_MAX_REQUEST_SIZE = 1024