PEER_SERVER_MAX_CONNECTION = 10
PEER_SERVER_TIMEOUT = 3

METAINFO_FILE_PATH = "metainfo/"
REPO_FILE_PATH = "repo/"

ANNOUNCE_INTERVAL = 60

TEMP_DOWNLOAD_FILE_EXTENSION = ".temp"

#? Piece size plus 1KB for other fields
PEER_WIRE_MESSAGE_SIZE = 65536 + 1024

PEER_CLIENT_MAX_CONNECTION = 10
PEER_CLIENT_CONNECTION_TIMEOUT = 120